# Generated by Django 5.1.2 on 2024-10-25 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='assign_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(related_name='tasks', to='category.category'),
        ),
    ]
